In [1]:
import numpy as np

In [10]:
np.set_printoptions(precision=2) # set print options for NumPy

n = 5
r = 3

W = abs(np.random.randn(n, r))
norm_vec = np.sum(W, axis=0)   
W = W / norm_vec[None, :] # normalizeing columns of W matrix
                          # each column has sum equals to unity

print('W:')
print(W)

W:
[[ 0.32  0.26  0.6 ]
 [ 0.25  0.19  0.09]
 [ 0.04  0.19  0.03]
 [ 0.34  0.26  0.08]
 [ 0.05  0.09  0.19]]


In [11]:
print('The vector s will be the first column of matrix W.')
s = W[:,0]
print('s:')
print(s)

The vector s will be the first column of matrix W.
s:
[ 0.32  0.25  0.04  0.34  0.05]


In [12]:
print('Constant values:\n')

sparse_W = 0.85
print('sparse_W: %1.2f' % sparse_W)

# L1 norm to achieve desired sparseness
L1_W = np.sqrt(n) - (np.sqrt(n)-1)*sparse_W
print('L1_W: %1.2f' % L1_W)


k1 = sum(abs(s))
k2 = sum(np.power(s,2))
print('k1: %1.2f' % k1)
print('k2: %1.2f' % k2)

Constant values:

sparse_W: 0.85
L1_W: 1.19
k1: 1.00
k2: 0.29


In [13]:
def project_func(s, k1, k2, non_negative):
    """
    Solves the following problem:
    
    Given a vector s, find the vector v having sum(abs(v))=k1
    and sum(v.^2)=k2 which is the closest to s in the euclidean
    sense.
    
    If the binary flag 'non-negative' is set, the vector v is
    additionally set to be non-negative.
    """
    print '---------------'
    print('Start Function:')
    print '---------------'
    # problem dimension
    N = len(s)
        
    if not non_negative:
        is_negative = s<0
        s = abs(s)
        
    # start by projecting the point to the sum constrained hyperplane
    v = (s + (k1 - sum(s))) / N
    print 'start v:'
    print v
    print '\n'
    
    # initialize zero_coeff
    zero_coeff = []
    
    j = 0
    while True:
        print 'zero_coeff:'
        print zero_coeff
        
        midpoint = (np.ones(N)*k1) / (N - len(zero_coeff))
        midpoint[zero_coeff] = 0
        print 'midpoint:'
        print midpoint
        
        w = v - midpoint  # vector
        a = sum(np.power(w,2)) # scalar
        b = 2 * (w.dot(v)) # scalar
        c = sum(np.power(v,2)) - k2 # scalar
        
        b2 = np.power(b, 2)
        ac = a * c # scalar
        
        print '\nEquation:'
        print 'b^2 = %1.2f' % b2
        print '4ac = %1.2f' % (4 * ac)
        delta = b2 - (4*ac)
        print 'delta = %1.2f' % delta
        
        alpha = (-b + np.real(np.sqrt(delta))) / (2*a)
        print 'alpha = %1.2f\n' % alpha
        
        v = alpha*w + v
        print 'new v:'
        print v
        
        # check if all components of v are non-negative
        if (v >= 0).all():
            print("We've found our solution.")
            used_iters = j+1
            break
        
        j = j+1
        
        # set negative values to zero, subtract appropriate amout from rest
        zero_coeff = np.where(v<=0)
        v[zero_coeff] = 0
        
        c = (k1 - sum(v)) / (N - len(zero_coeff))
        v = (v + c)
        v[zero_coeff] = 0
        print 'v after c'
        print v
        
    # if binary flag not set, return signs to the solution
    if not non_negative:
        v = ((-2*is_negative) + 1) * v;
        
    # check for problems
    if np.max(abs(np.imag(v))) > e-10:
        print('Somehow got imaginary values.')
    
    return v

In [14]:
project_func(s, L1_W, k2, 1)

---------------
Start Function:
---------------
start v:
[ 0.1   0.09  0.04  0.11  0.05]


zero_coeff:
[]
midpoint:
[ 0.24  0.24  0.24  0.24  0.24]

Equation:
b^2 = 0.01
4ac = -0.13
delta = 0.15
alpha = 1.90

new v:
[-0.16 -0.2  -0.32 -0.14 -0.31]
v after c
[ 0.  0.  0.  0.  0.]
zero_coeff:
(array([0, 1, 2, 3, 4]),)
midpoint:
[ 0.  0.  0.  0.  0.]

Equation:
b^2 = 0.00
4ac = -0.00
delta = 0.00
alpha = nan

new v:
[ nan  nan  nan  nan  nan]
v after c
[ nan  nan  nan  nan  nan]
zero_coeff:
(array([], dtype=int64),)
midpoint:
[ 0.3  0.3  0.3  0.3  0.3]

Equation:
b^2 = nan
4ac = nan
delta = nan
alpha = nan

new v:
[ nan  nan  nan  nan  nan]
v after c
[ nan  nan  nan  nan  nan]
zero_coeff:
(array([], dtype=int64),)
midpoint:
[ 0.3  0.3  0.3  0.3  0.3]

Equation:
b^2 = nan
4ac = nan
delta = nan
alpha = nan

new v:
[ nan  nan  nan  nan  nan]
v after c
[ nan  nan  nan  nan  nan]
zero_coeff:
(array([], dtype=int64),)
midpoint:
[ 0.3  0.3  0.3  0.3  0.3]

Equation:
b^2 = nan
4ac = nan
delta = n

/home/phil/Software/miniconda2/lib/python2.7/site-packages/ipykernel/__main__.py:55: RuntimeWarning: invalid value encountered in double_scalars
/home/phil/Software/miniconda2/lib/python2.7/site-packages/ipykernel/__main__.py:63: RuntimeWarning: invalid value encountered in greater_equal
/home/phil/Software/miniconda2/lib/python2.7/site-packages/ipykernel/__main__.py:71: RuntimeWarning: invalid value encountered in less_equal


array([ nan,  nan,  nan,  nan,  nan])

In [15]:
W

array([[ 0.32,  0.26,  0.6 ],
       [ 0.25,  0.19,  0.09],
       [ 0.04,  0.19,  0.03],
       [ 0.34,  0.26,  0.08],
       [ 0.05,  0.09,  0.19]])

In [19]:
np.sqrt(sum(np.power(W, 2)))

array([ 0.54,  0.47,  0.65])

In [22]:
1e-10 + 1

1.0000000001

In [28]:
s.dot(s)

0.25755534272942898