In [1]:
import numpy as np

In [72]:
def project_func(s, k1, k2, non_negative):
    """
    Solves the following problem:
    
    Given a vector s, find the vector v having sum(abs(v))=k1
    and sum(v.^2)=k2 which is the closest to s in the euclidean
    sense.
    """
    print('Start Function:\n')
    # problem dimension
    N = len(s)
        
    if not non_negative:
        is_negative = s<0
        s = abs(s)
        
    # start by projecting the point to the sum constrained hyperplane
    v = (s + (k1 - sum(s))) / N
    print 'start v:'
    print v
    
    # initialize zero_coeff
    zero_coeff = []
    
    j = 0
    while True:
        print 'zero_coeff:'
        print zero_coeff
        
        midpoint = (np.ones(N)*k1) / (N - len(zero_coeff))
        midpoint[zero_coeff] = 0
        print 'midpoint:'
        print midpoint
        
        w = v - midpoint
        a = sum(np.power(w,2))
        b = 2*w.T.dot(v)
        c = sum(np.power(v,2)) - k2
        b2 = np.power(b, 2)
        ac = a * c 
        
        print 'a:'
        print a
        print 'b2:'
        print b2
        print '4ac:'
        print '%1.3f' % (4*ac)
        
        alpha = (-b + np.real(np.sqrt(b2 - 4*ac))) / (2*a)
        print 'alpha:'
        print alpha
        
        v = alpha*w + v
        print 'v:'
        print v
        
        j = j+1
        
        # set negative values to zero, subtract appropriate amout from rest
        zero_coeff = np.where(v<=0)
        v[zero_coeff] = 0
        
        c = (k1 - sum(v)) / (N - len(zero_coeff))
        print 'c'
        print c
        v = (v + c)
        print 'v'
        print v
        
        print('')
        if j == 5:
            break
    
    
    return 0

In [63]:
np.set_printoptions(precision=3)
W = abs(np.random.randn(8, 3))
norm_vec = np.sum(W, axis=0)
W = W / norm_vec[None, :]
print(W)

[[ 0.147  0.263  0.202]
 [ 0.199  0.017  0.029]
 [ 0.014  0.051  0.067]
 [ 0.293  0.178  0.15 ]
 [ 0.047  0.26   0.353]
 [ 0.047  0.116  0.065]
 [ 0.236  0.017  0.109]
 [ 0.016  0.098  0.025]]


In [64]:
s = W[:,0]
print(len(s))

8


In [76]:
sparse_W = 0.9
print('sparse_W: %1.3f' % sparse_W)
n = W.shape[0]
r = W.shape[1]
L1_W = np.sqrt(n) - (np.sqrt(n)-1)*sparse_W
print('L1_W: %1.3f' % L1_W)
k1 = sum(abs(s))
k2 = sum(np.power(s,2))
print('k1: %1.3f' % k1)
print('k2: %1.3f' % k2)

sparse_W: 0.900
L1_W: 1.183
k1: 1.000
k2: 0.208


In [77]:
project_func(s, L1_W, k2, 1)

Start Function:

start v:
[ 0.041  0.048  0.025  0.06   0.029  0.029  0.052  0.025]
zero_coeff:
[]
midpoint:
[ 0.148  0.148  0.148  0.148  0.148  0.148  0.148  0.148]
a:
0.0969988298882
b2:
0.00419245677394
4ac:
-0.076
alpha:
1.78961271427
v:
[-0.15  -0.131 -0.196 -0.099 -0.184 -0.184 -0.119 -0.195]
c
0.168977530354
v
[ 0.169  0.169  0.169  0.169  0.169  0.169  0.169  0.169]

zero_coeff:
(array([0, 1, 2, 3, 4, 5, 6, 7]),)
midpoint:
[ 0.  0.  0.  0.  0.  0.  0.  0.]
a:
0.228427246115
b2:
0.208716027071
4ac:
0.019
alpha:
-0.0459315796953
v:
[ 0.161  0.161  0.161  0.161  0.161  0.161  0.161  0.161]
c
-0.0152694701623
v
[ 0.146  0.146  0.146  0.146  0.146  0.146  0.146  0.146]

zero_coeff:
(array([], dtype=int64),)
midpoint:
[ 0.169  0.169  0.169  0.169  0.169  0.169  0.169  0.169]
a:
0.00424336964989
b2:
0.00289233862478
4ac:
-0.001
alpha:
13.3370000002
v:
[-0.161 -0.161 -0.161 -0.161 -0.161 -0.161 -0.161 -0.161]
c
0.168977530354
v
[ 0.169  0.169  0.169  0.169  0.169  0.169  0.169  0.169]

0

0.19356601717798214